[package]
name = "spaceout"
version = "1.0.0"
authors = ["Jia Ye <planet0104@gmail.com>"]
edition = "2018"

[dependencies]
mengine = { git = "https://github.com/planet0104/mengine" }

[profile.release]
lto = true
opt-level = 's'
panic = 'abort'